accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.decorators import login_required
from . import views

app_name = "accounts"
urlpatterns = [
    path("create/", views.AccountCreate.as_view(), name="create"),
    path("login/", views.AccountLogin.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", login_required(views.AccountProfile.as_view(), login_url=reverse_lazy("accounts:login")), name="profile"),
    path("update/<int:pk>/", login_required(views.AccountUpdate.as_view()), name="update"),
    path("delete/<int:pk>/", login_required(views.AccountDelete.as_view()), name="delete"),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("integration/", include("recipe_integration.urls")),
    path('account/', include("accounts.urls")),
    path('admin/', admin.site.urls),
]

recipe_integration/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "recipe_int"
urlpatterns = [
    path("recipe/", login_required(views.main), name="main"),
    path("recipe/fetch/<int:recipe_id>", login_required(views.recipe_fetch), name="recipe_fetch"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

recipe_integration/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class UserCreationCustomForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "email",)

recipe_integration/forms.py
from django import forms


class RecipeFetchForm(forms.Form):
    recipe_id = forms.IntegerField(widget=forms.TextInput(attrs={"required": True, "type": "number", "min": 0,}), required=True, label="Recipe ID", min_value=0)

accounts/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect

from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy

from . import forms



class AccountCreate(CreateView):
    model = User
    form_class = forms.UserCreationCustomForm
    template_name = "create.html"
    success_url = reverse_lazy("accounts:login")


class AccountLogin(LoginView):
    template_name = "login.html"
    success_url = reverse_lazy("accounts:profile")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(redirect_to=reverse_lazy("accounts:login"))


class AccountProfile(TemplateView):
    template_name = "profile.html"  


class AccountUpdate(UpdateView):
    model = User
    fields = ("username", "email",)
    template_name = "update.html"
    success_url = reverse_lazy("accounts:profile")
    

class AccountDelete(DeleteView):
    model = User
    template_name = "delete.html"
    success_url = reverse_lazy("accounts:login")

recipe_integration/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import generic
from . import forms, utils



def main(request):
    if request.method == "POST":
        form = forms.RecipeFetchForm(request.POST)
        # Validate the input first before the redirect
        if form.is_valid():
            return HttpResponseRedirect(f"fetch/{form.cleaned_data['recipe_id']}")
    else:
        form = forms.RecipeFetchForm()
        return render(request, "main.html", {"form": form})


def recipe_fetch(request, recipe_id):
    name, servings, ingredients, amount = utils.get_ingredients(recipe_id)
    api_data = []
    # Store the ingredient and its corresponding amoun in the dictionary
    ingredients = {ingredient: amount for (ingredient, amount) in zip(ingredients, amount)}
    # Iterate over the dictionary to get the correct data from API
    for ingredient, amount in ingredients.items():
        data = utils.get_result(item_name=ingredient, item_amount=amount, recipe_id=recipe_id, local_cache=True)
        api_data.extend(data)
    return render(request, "ingredients.html", context={"fetch_data": api_data, "serving": servings, "name": name,})

accounts/templates/account_create.html
{% extends 'base.html' %}
{% block title %}Create a New Account{% endblock %}
{% block content %}
<h2>Create a New Account<h2/>
<form method='POST'>
    {% csrf_token %} {{ form }}
    <input type='submit' value='Create Account' />
</form>
{% endblock %}

accounts/templates/account_login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<h2>Login</h2>
<form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Login" />
</form>
{% endblock %}

accounts/templates/create.html
{% extends 'base.html' %}
{% block title %}Create a New Account{% endblock %}
{% block content %}
<div class="control">
    <h2>Create a New Account</h2>
    <form method='POST'>
        {% csrf_token %} {{ form }}
        <input type='submit' value='Create Account' />
    </form>
    <p>
        Already have an account?
        <a href="{% url 'accounts:login' %}">Click here</a>
    </p>
</div>
<script>
    $('[type="text"]').attr("placeholder", "Username");
    $('[type="email"]').attr("placeholder", "Email");
    $('[type="password"]').eq(0).attr("placeholder", "Password");
    $('[type="password"]').eq(1).attr("placeholder", "Password (Confirmation)");
    $('label').hide();
    $('span').hide();
    $('br').hide();
    $('.helptext').hide();
</script>
{% endblock %}

accounts/templates/delete.html
{% extends 'base.html' %}
{% block title %}Account Deletion {% endblock %}
{% block content %}
<div class="control">
    <h2>Confirmation</h2>
    <form method='POST'>
        {% csrf_token %}  
        <p>Are you sure you want to delete your account?</p>
        {{ form }}
        <input type='submit' value='Delete Account'>
    </form>
    <a href="{% url 'accounts:profile' %}">No, go back</a>
</div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="control">
    <h2>Login</h2>
    <form method="POST">
        {% csrf_token %} {{ form }}
        <a href="{% url 'accounts:create' %}">control Up</a>
        <input type="submit" value="Login" />
    </form>
</div>
<div class="profile">
    <a href="{% url 'accounts:create' %}">Create an account</a>
</div>
<script>
    $('[type="text"]').attr("placeholder", "Username");
    $('[type="password"]').attr("placeholder", "Password");
    $('form a').hide();
    $('label').hide();
    $('span').hide();
    $('br').hide();
</script>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="profile">
    <h2>Account Page</h2>
    <section>
        <aside>
            <p>Username:</p>
            <strong>{{user.username}}</strong>
        </aside>
        <aside>
            <p>Email:</p>
            <strong>{{user.email}}</strong>
        </aside>
        <aside class="profile_date">
            <p>Registered at:</p>
            <strong>{{user.date_joined}}</strong>
        </aside>
    </section>
    <a href="{% url 'accounts:update' user.id %}">Update Profile</a>
    <a href="{% url 'accounts:logout' %}">Logout</a>
    <a href="{% url 'accounts:delete' user.id %}">Delete Account</a>
    <a href="{% url 'recipe_int:main' %}">Recipe Search</a>
</div>
{% endblock %}

accounts/templates/update.html
{% extends 'base.html' %}
{% block title %}Update Accout Information{% endblock %}
{% block content %}
<div class="control">
    <h2>Update Account</h2>
    <form method='POST'>
        {% csrf_token %}
        {{ form }}
        <input type='submit' value='Update'>
    </form>
    <a href="{% url 'accounts:profile' %}">Cancel</a>
</div>
<script>
    $('label').hide();
    $('span').hide();
    $('br').hide();
    $('.helptext').hide();
</script>
{% endblock %}

recipe_integration/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.7.1.js"
    integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
    crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <h3>Recipe-Ichiba Assistant</h3>
    </header>
    {% block content %}
    {% endblock %}
</body>
<footer>
    <p>@Powered by Rakuten</p>
</footer>
</html>

recipe_integration/templates/ingredients.html
{% extends 'base.html' %}
{% block title %}Ingridients Page{% endblock %}

{% block content %}
<div class="ingredient">
    <h3 class="fixed">合計金額 : <strong class="estimation"></strong>円</h3>
    <h2>{{ name }}</h2>
    <h4>{{ serving }}</h4>
    {% regroup fetch_data by product_name as result_list %}
    <ul>
        {% for product_name in result_list %}
            <hr>
            <aside>
                <button class="controlDisplay">+</button>
                <li> {{ product_name.grouper }}: {{ product_name.list.0.product_amount }}</li>
            </aside>
            <section class="hide">
                <blockquote class="menu_containter">
                    <button class="hamburger">ソート ▽</button>
                    <nav class="menu">
                        <button class="priceUp">値段↑</button>
                        <button class="priceDown">値段↓</button>
                        <button class="starUp">評価↑</button>
                        <button class="starDown">評価↓</button>
                    </nav>
                </blockquote>
                <section>
                    {% for result in product_name.list %}
                    <figure>
                        <img src={{ result.mediumImg }}>
                        <figcaption>
                            <a href={{ result.url }}>{{ result.name }}</a>
                            <aside>
                                <p class="price">{{ result.price }}円</p>
                                <p class="star">☆{{ result.score }}</p>
                            </aside>
                        </figcaption>
                        <button class="checkbox"></button>
                    </figure>
                    {% endfor %}
                </section>
            </section>
        {% endfor %}
        <hr>
    </ul>
</div>
<div class="profile">
    <a href="{% url 'recipe_int:main' %}">Back</a>
</div>
<script>
    $('.controlDisplay').click((e)=>{
        if($(e.target).text() == "+"){
            $(e.target).text("-");
            $(e.target).parent().next().css("display", "flex")
        }else{
            $(e.target).text("+");
            $(e.target).parent().next().css("display", "none")
        }
    })

    $('.hamburger').on('click', function(e){
        $('.menu').slideToggle();
        let triangle = $(e.target).text().slice(-1);
        if(triangle == "▽"){
            $(e.target).text("ソート △");
        }else{
            $(e.target).text("ソート ▽");
        }
    });

    $('.priceUp').click((e)=>{
        let priceTag = $(e.target.parentElement.parentElement.parentElement).find('.price');
        let section = $(e.target.parentElement.parentElement).next();
        let figureTags = $(e.target.parentElement.parentElement.parentElement).find('figure');
        for(let i = 0; i < 10; i++){
            let price = priceTag.eq(i).text().slice(0, -1);
            figureTags.eq(i).removeClass();
            figureTags.eq(i).addClass(price);
        }
        figureTags.sort(function(a,b){
            var figureA = parseInt($(a).attr('class').match(/\d+/));
            var figureB = parseInt($(b).attr('class').match(/\d+/));
            return figureA - figureB;
        })
        section.html(figureTags);
    })
    
    $('.priceDown').click((e)=>{
        let priceTag = $(e.target.parentElement.parentElement.parentElement).find('.price');
        let section = $(e.target.parentElement.parentElement).next();
        let figureTags = $(e.target.parentElement.parentElement.parentElement).find('figure');
        for(let i = 0; i < 10; i++){
            let price = priceTag.eq(i).text().slice(0, -1);
            figureTags.eq(i).removeClass();
            figureTags.eq(i).addClass(price);
        }
        figureTags.sort(function(a,b){
            var figureA = parseInt($(a).attr('class').match(/\d+/));
            var figureB = parseInt($(b).attr('class').match(/\d+/));
            return figureB - figureA;
        })
        section.html(figureTags);
    })
    
    $('.starUp').click((e)=>{
        let starTag = $(e.target.parentElement.parentElement.parentElement).find('.star');
        let section = $(e.target.parentElement.parentElement).next();
        let figureTags = $(e.target.parentElement.parentElement.parentElement).find('figure');
        for(let i = 0; i < 10; i++){
            let star = starTag.eq(i).text().slice(1);
            figureTags.eq(i).removeClass();
            figureTags.eq(i).addClass(star);
        }
        figureTags.sort(function(a,b){
            var figureA = $(a).attr('class');
            var figureB = $(b).attr('class');
            return figureA - figureB;
        })
        section.html(figureTags);
    })

    $('.starDown').click((e)=>{
        let starTag = $(e.target.parentElement.parentElement.parentElement).find('.star');
        let section = $(e.target.parentElement.parentElement).next();
        let figureTags = $(e.target.parentElement.parentElement.parentElement).find('figure');
        for(let i = 0; i < 10; i++){
            let star = starTag.eq(i).text().slice(1);
            figureTags.eq(i).removeClass();
            figureTags.eq(i).addClass(star);
        }
        figureTags.sort(function(a,b){
            var figureA = $(a).attr('class');
            var figureB = $(b).attr('class');
            return figureB - figureA;
        })
        section.html(figureTags);
    })
    let totalPrice = 0;
    $(".estimation").text(totalPrice);
    $(document).on('click', '.checkbox', (e) => {
        $(e.target).toggleClass('selected');
        let price = Number($(e.target).parent().find('.price').text().slice(0, -1));
        if($(e.target).attr("class") == "checkbox selected"){
            totalPrice += price;
        }else if($(e.target).attr("class") == "checkbox"){
            totalPrice -= price;
        }
        $(".estimation").text(totalPrice);
    });
    
</script>
{% endblock %}

recipe_integration/templates/main.html
{% extends 'base.html' %}
{% block title %}Ingridients Page{% endblock %}
{% block content %} 

<div class="search-bar">
    <h2>Enter the recipe ID: </h2>
    <form action="http://127.0.0.1:8000/integration/recipe/" method="POST" >
        {% csrf_token %} {{ form }}
        <input type="submit" value="Get Ingridients">
    </form>
</div>
<div class="profile">
    <a href="{% url 'accounts:profile'%}">Go To Your Profile</a>
    </div>
<script>
    $('[type="text"]').attr("placeholder", "Type Recipe ID here");
    $('label').hide();
</script>
{% endblock %}